server:
  servlet:
    session:
      timeout: 1800
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    #创建数据库连接，连接到springboot数据库
    url: jdbc:mysql://localhost:3306/websocket
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl